### ISSUE TITLE
Menu icon is rendering to the right of the appbar title at mobile viewports

### ISSUE THREAD

**Issue by daileytj** [brightlayer-ui/react-showcase-demo#31]
#### Describe the bug
Menu icon is rendering to the right of the appbar title at mobile width.

#### What is the expected behavior?
The menu icon should render to the left of the appbar title at mobile width.

#### What are the steps to reproduce?
1. Clone the repo & cd into it.
2. Run `yarn && yarn start`
3. Shrink window to less than 600px width
4. Observe menu icon in the wrong position

#### Screenshots or links to minimum reproduction example
![Screen Shot 2022-01-12 at 2 18 46 PM](https://user-images.githubusercontent.com/13989985/149223657-49d7b2de-e84a-4b1c-9e22-4332016ed093.png)

**Comment by AlanLes** [comment]
What's the correct position for this Menu element? Should it be aligned to the right? :)

**Comment by IanFindlay** [comment]
Just seen that @AlanLes has also worked on / fixed this issue. Regardless of whether or not my change - menu icon on the left of the title - is the correct interpretation feel free to allow them to update their PR and merge that one if you like as they were first.

**Comment by AlanLes** [comment]
Okay, great, thanks!

**Comment by joebochill** [comment]
Yes, the icon should be on the left of the text, like this:
<img width="364" alt="image" src="https://user-images.githubusercontent.com/29152776/193411220-3e1a188a-6807-4a11-8a55-76746d7336f2.png">
