### ISSUE TITLE
Table header checkbox and text has more space

### ISSUE THREAD

**Issue by bkarambe** [brightlayer-ui/react-showcase-demo#34]
#### Describe the bug
The space between the **checkbox** and **table header text** is larger than the space between the **checkbox** and **table data text** 

#### What is the expected behavior?
The space between the **checkbox** and **table header text** should be same as the space between the **checkbox** and **table data text** 

#### What are the steps to reproduce?
1. yarn start
2. Go to Material Components --> Data Display --> Table

#### Screenshots or links to minimum reproduction example
<img width="1792" alt="Screenshot 2022-02-02 at 1 46 23 PM" src="https://user-images.githubusercontent.com/25982779/152118180-a28004a3-c688-4951-80b5-51017260d93f.png">

#### Environment

It is happening for the desktop as well as mobile 
		
#### Anything else to add?
No

**Comment by jeffvg** [comment]
this has been fixed in above PR
