### ISSUE TITLE
codesandbox link is breaking 

### ISSUE THREAD

**Issue by ektasawant** [brightlayer-ui/react-showcase-demo#36]
#### Describe the bug
https://codesandbox.io/s/github/brightlayer-ui/react-showcase-demo link is not working.
#### What are the steps to reproduce?
1. Go to https://codesandbox.io/s/github/brightlayer-ui/react-showcase-demo

#### Screenshots or links to minimum reproduction example

<img width="1683" alt="Screenshot 2022-02-02 at 7 12 14 PM" src="https://user-images.githubusercontent.com/10433274/152165082-f5b1ee73-54f9-48e9-b03b-045fbe7ba2fd.png">

#### Environment

All

**Comment by jeffvg** [comment]
let wait and see if MUIv5 fixes this

**Comment by huayunh** [comment]
Can confirm v5 works on CSB: https://codesandbox.io/s/github/brightlayer-ui/react-showcase-demo/tree/mui-v5 
closing the issue
