### ISSUE TITLE
eslint rules should not silence the "react/jsx-key" rule

### ISSUE THREAD

**Issue by daileytj** [brightlayer-ui/react-showcase-demo#44]
#### Describe the bug
The eslint "react/jsx-key" rule has been temporarily set to false in the .eslintrc.js file to temporarily mute a known issue in `eslint-plugin-react@7.29.0` linked at the bottom of this issue description.

#### What is the expected behavior?
This rule should not be disabled and there should be no linting errors when running `yarn lint`. 

#### How to Recreate
1. Clone this repo
2. Remove the line in the file '.eslintrc.js' that disables the 'react/jsx-key' rule.
3. Run `yarn && yarn lint`
4. Observe the errors in the console.

#### Anything else to add?
https://github.com/yannickcr/eslint-plugin-react/issues/3215
https://github.com/facebook/create-react-app/issues/11825

Updating to version ^7.29.2 should fix the issue.

**Comment by joebochill** [comment]
@daileytj 7.29.2 of eslint-plugin-react seems to fix the underlying issue for this.

**Comment by AlanLes** [comment]
Hello, can I please take this one? :) Please assign it to me ;)

**Comment by joebochill** [comment]
It looks like you might have two versions of the plugin installed. Did you use yarn to install/update the version (if you used npm, you might have created a second copy)?

For this issue, you should be able to just bump the plugin version in package.json, run `yarn` to update the lockfile, and then remove the `'react/jsx-key': 'off'` rule in eslintrc.js

**Comment by joebochill** [comment]
I see what you were talking about now (when running the app). That looks like it's caused because the latest-version of react-scripts depends on an older version of the eslint-plugin-react. Changing `^7.29.2` to `~7.29.2` got us the latest 7.29 version (with the fix we needed) but didn't jump all the way to 7.31 which react-scripts won't allow yet.

**Comment by AlanLes** [comment]
Yep, but it happened even if I updated to the mentioned by you, latest version `7.31.8`. Because, you know, that was my first shot. I initially thought: "Why to bump this only to `7.29.2`? Let's bump it to the latest and check what's gonna explode".  😅
