### ISSUE TITLE
Update hero component to add ChannelValueProps

### ISSUE THREAD

**Issue by ektasawant** [brightlayer-ui/react-showcase-demo#51]
#### Describe the desired behavior
Update Hero component to add ChannelValueProps

https://github.com/brightlayer-ui/react-component-library/issues/365

**Comment by ektasawant** [comment]
This is fixed in https://github.com/brightlayer-ui/react-showcase-demo/blob/feature/2711-upgrate-mui-to-v5/src/components/brightlayer-ui/data-display/Hero.tsx#L52

**Comment by bkarambe** [comment]
This is already been addressed.
