### ISSUE TITLE
Fix performance issue after mui v5 migration and pass correct type to style objects 

### ISSUE THREAD

**Issue by bkarambe** [brightlayer-ui/react-showcase-demo#86]
#### Describe the bug
There is a performance issue in react-showcase-demo while navigating from one page to another. This got introduced during mui v5 migration.
Styled objects passed to sx props should have correct type and should throw error, when incorrect styles are passed

#### What is the expected behavior?
All pages should render smoothly without a lag. 
An error should occur, when incorrect styles are being passed to style objects

#### What are the steps to reproduce?
1. yarn start
2. Click on the various drawer nav items, change direction to navigate to different pages/directions

#### Screenshots or links to minimum reproduction example

https://user-images.githubusercontent.com/25982779/177985364-942b5b9a-5d26-4686-8415-04bb5fbcb2a9.mov

**Comment by bkarambe** [comment]
Use this issue to remove CacheProvider.

**Comment by huayunh** [comment]
BLUI-3356
